const favorites = [
    {
        id: '01',
        name: 'THE BOOK EATERS',
        author: 'Sunyi Dean',
        description : 'An unusual sci-fi story about a book eater woman who tries desperately to save her dangerous mind-eater son from tradition and certain death. Complete with dysfunctional family values, light Sapphic romance, and a strong, complex protagonist. Not for the faint of heart.',
        poster : './img/book-winter-1.jpg',
        season: 'winter',
    },
    {
        id: '02',
        name: 'Cackle',
        author: 'Rachel Harrison',
        description : 'Are your Halloween movies of choice The Witches of Eastwick and Practical Magic? Look no further than here - where a woman recovering from a breakup moves to a quaint town in upstate New York and befriends a beautiful witch.',
        poster : './img/book-winter-2.jpg',
        season: 'winter',
    },
    {
        id: '03',
        name: 'Dante: Poet of the Secular World',
        author: 'Erich Auerbach',
        description : 'Auerbach\'s engaging book places the \'Comedy\' within the tradition of epic, tragedy, and philosophy in general, arguing for Dante\'s uniqueness as one who raised the individual and his drama of soul into something of divine significance—an inspired introduction to Dante\'s main themes.',
        poster : './img/book-winter-3.jpg',
        season: 'winter',
    },
    {
        id: '04',
        name: 'The Last Queen',
        author: 'Clive Irving',
        description : 'A timely and revelatory new biography of Queen Elizabeth (and her family) exploring how the Windsors have evolved and thrived as the modern world has changed around them.',
        poster : './img/book-winter-4.jpg',
        season: 'winter',
    },
    {
        id: '05',
        name: 'The Body',
        author: 'Stephen King',
        description : 'Powerful novel that takes you back to a nostalgic time, exploring both the beauty and danger and loss of innocence that is youth.',
        poster : './img/book-spring-1.jpg',
        season: 'spring',
    },

    {
        id: '06',
        name: 'Carry: A Memoir of Survival on Stolen Land',
        author: 'Toni Jenson',
        description : 'This memoir about the author\'s relationship with gun violence feels both expansive and intimate, resulting in a lyrical indictment of the way things are.',
        poster : './img/book-spring-2.jpg',
        season: 'spring',
    },
    {
        id: '07',
        name: 'Days of Distraction',
        author: 'Alexandra Chang',
        description : 'A sardonic view of Silicon Valley culture, a meditation on race, and a journal of displacement and belonging, all in one form-defying package of spare prose.',
        poster : './img/book-spring-3.jpg',
        season: 'spring',
    },
    {
        id: '08',
        name: 'Dominicana',
        author: 'Angie Cruz',
        description : 'A fascinating story of a teenage girl who marries a man twice her age with the promise to bring her to America. Her marriage is an opportunity for her family to eventually immigrate. For fans of Isabel Allende and Julia Alvarez.',
        poster : './img/book-spring-4.jpg',
        season: 'spring',
    },
    {
        id: '09',
        name: 'Crude: A Memoir',
        author: 'Pablo Fajardo & Sophie Tardy-Joubert',
        description : 'Drawing and color by Damien Roudeau | This book illustrates the struggles of a group of indigenous Ecuadoreans as they try to sue the ChevronTexaco company for damage their oil fields did to the Amazon and her people',
        poster : './img/book-summer-1.jpg',
        season: 'summer',
    },
    {
        id: '10',
        name: 'Let My People Go Surfing',
        author: 'Yvon Chouinard',
        description : 'Chouinard—climber, businessman, environmentalist—shares tales of courage and persistence from his experience of founding and leading Patagonia, Inc. Full title: Let My People Go Surfing: The Education of a Reluctant Businessman, Including 10 More Years of Business Unusual.',
        poster : './img/book-summer-2.jpg',
        season: 'summer',
    },
    {
        id: '11',
        name: 'The Octopus Museum: Poems',
        author: 'Brenda Shaughnessy',
        description : 'This collection of bold and scathingly beautiful feminist poems imagines what comes after our current age of environmental destruction, racism, sexism, and divisive politics.',
        poster : './img/book-summer-3.jpg',
        season: 'summer',
    },
    {
        id: '12',
        name: 'Shark Dialogues: A Novel',
        author: 'Kiana Davenport',
        description : 'An epic saga of seven generations of one family encompasses the tumultuous history of Hawaii as a Hawaiian woman gathers her four granddaughters together in an erotic tale of villains and dreamers, queens and revolutionaries, lepers and healers.',
        poster : './img/book-summer-4.jpg',
        season: 'summer',
    },
    {
        id: '13',
        name: 'Casual Conversation',
        author: 'Renia White',
        description : 'White\'s impressive debut collection takes readers through and beyond the concepts of conversation and the casual - both what we say to each other and what we don\'t, examining the possibilities around how we construct and communicate identity. ',
        poster : './img/book-autumn-1.jpg',
        season: 'autumn',
    },
    {
        id: '14',
        name: 'The Great Fire',
        author: 'Lou Ureneck',
        description : 'The harrowing story of an ordinary American and a principled Naval officer who, horrified by the burning of Smyrna, led an extraordinary rescue effort that saved a quarter of a million refugees from the Armenian Genocide',
        poster : './img/book-autumn-2.jpg',
        season: 'autumn',
    },
    {
        id: '15',
        name: 'Rickey: The Life and Legend',
        author: 'Howard Bryant',
        description : 'With the fall rolling around, one can\'t help but think of baseball\'s postseason coming up! And what better way to prepare for it than reading the biography of one of the game\'s all-time greatest performers, the Man of Steal, Rickey Henderson?',
        poster : './img/book-autumn-3.jpg',
        season: 'autumn',
    },
    {
        id: '16',
        name: 'Slug: And Other Stories',
        author: 'Megan Milks',
        description : 'Exes Tegan and Sara find themselves chained together by hairballs of codependency. A father and child experience the shared trauma of giving birth to gods from their wounds.',
        poster : './img/book-autumn-4.jpg',
        season: 'autumn',
    },
]
